INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

INSERT into users (username, email, password) VALUES ('Alice', 'alice@gamil.com', '$2a$12$9CHk.045yPPmn82kA6L5H.o5JqZkhySM7genfaE6WcD86mYIpB/pm');
INSERT into users (username, email, password) VALUES ('anooj', 'alice@gamil.com', '$2a$12$9CHk.045yPPmn82kA6L5H.o5JqZkhySM7genfaE6WcD86mYIpB/pm');

INSERT INTO user_roles(user_id, role_id) VALUES (1, 1);
INSERT INTO user_roles(user_id, role_id) VALUES (1, 2);
INSERT INTO user_roles(user_id, role_id) VALUES (2, 1);

-- post
INSERT INTO post (title, content, user_id) VALUES ('Getting started with Spring Boot', 'Intro guide to building REST APIs with Spring Boot.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Maven build tips', 'Useful tips to speed up and optimize Maven builds.', 2);
INSERT INTO post (title, content, user_id) VALUES ('JPA entity mappings', 'Guide on one-to-many and many-to-many relationships.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Bean validation basics', 'Using javax validation annotations in DTOs.', 2);
INSERT INTO post (title, content, user_id) VALUES ('Testing with JUnit 5', 'Structuring unit and integration tests.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Spring Security overview', 'Configuring authentication and authorization.', 2);
INSERT INTO post (title, content, user_id) VALUES ('Flyway vs Liquibase', 'Pros and cons for database migrations.', 1);
INSERT INTO post (title, content, user_id) VALUES ('DTO vs Entity', 'When to use DTOs and mapping strategies.', 2);
INSERT INTO post (title, content, user_id) VALUES ('REST error handling', 'Standardizing API error responses.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Pagination in Spring Data', 'Implementing pageable repositories.', 2);
INSERT INTO post (title, content, user_id) VALUES ('H2 for local dev', 'Using H2 for fast local prototyping.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Profiles in Spring', 'Managing `dev`, `test`, `prod` configurations.', 2);
INSERT INTO post (title, content, user_id) VALUES ('Logging with SLF4J', 'Best practices for application logging.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Actuator endpoints', 'Monitoring health and metrics.', 2);
INSERT INTO post (title, content, user_id) VALUES ('OpenAPI docs', 'Generating API docs with springdoc.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Exception handling', 'Global handlers with `@ControllerAdvice`.', 2);
INSERT INTO post (title, content, user_id) VALUES ('Caching with Spring', 'Using `@Cacheable` and cache providers.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Async tasks', 'Using `@Async` and thread pools.', 2);
INSERT INTO post (title, content, user_id) VALUES ('Scheduling jobs', 'Cron and fixed rate scheduling.', 1);
INSERT INTO post (title, content, user_id) VALUES ('Database indexing', 'Choosing indexes for performance.', 2);

-- comment (post_id references the order created above: 1..20)
INSERT INTO comment (content, post_id, user_id) VALUES ('Nice overview, thanks!', 1, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Add sample repo?', 1, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Helpful guide.', 2, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Use `-T` for parallel builds.', 2, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Clear explanation on relationships.', 3, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Show cascade examples.', 3, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Validation groups would be useful.', 4, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Include custom validators.', 4, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Please cover mocking.', 5, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Parametrized tests FTW.', 5, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('What about OAuth2?', 6, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('RBAC examples are great.', 6, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('We use Flyway in prod.', 7, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Liquibase changeSets are readable.', 7, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('MapStruct recommendation?', 8, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Avoid exposing entities.', 8, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Return RFC7807 in errors.', 9, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Include traceId.', 9, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Pageable is super handy.', 10, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Remember sorting.', 10, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('H2 console tip!', 11, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Seed data helps.', 11, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Profiles keep things clean.', 12, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Use `@ConfigurationProperties`.', 12, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Avoid logs in hot paths.', 13, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Structured logging rocks.', 13, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Actuator security reminders.', 14, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Expose only needed endpoints.', 14, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('springdoc simplifies a lot.', 15, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Add example schemas.', 15, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('ControllerAdvice saves time.', 16, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Map errors consistently.', 16, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Cache eviction strategies?', 17, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Show Redis example.', 17, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Async pitfalls?', 18, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Thread pool sizing matters.', 18, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Use cron expressions carefully.', 19, 2);
INSERT INTO comment (content, post_id, user_id) VALUES ('Add `@Scheduled` samples.', 19, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Index coverage matters.', 20, 1);
INSERT INTO comment (content, post_id, user_id) VALUES ('Measure before adding indexes.', 20, 2);
